# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build development IPA for internal testing"
  lane :build_development do
    # Set up App Store Connect API key
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: "AuthKey.p8",
      in_house: false
    )

    build_app(
      workspace: "App.xcworkspace",
      scheme: "Shift Scan",
      configuration: "Debug",
      export_method: "development",
      output_directory: "build",
      output_name: "ShiftScan-Dev.ipa",
      skip_package_ipa: false,
      skip_package_pkg: true,
      derived_data_path: "build/DerivedData",
      xcargs: "-allowProvisioningUpdates"
    )
  end

  desc "Build IPA for TestFlight"
  lane :build_testflight do
    # Set up App Store Connect API key
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: "AuthKey.p8",
      in_house: false
    )

    build_app(
      workspace: "App.xcworkspace",
      scheme: "Shift Scan",
      configuration: "Release",
      export_method: "app-store",
      output_directory: "build",
      output_name: "ShiftScan-TestFlight.ipa",
      skip_package_ipa: false,
      skip_package_pkg: true,
      derived_data_path: "build/DerivedData",
      xcargs: "-allowProvisioningUpdates"
    )
  end

  desc "Build IPA for App Store"
  lane :build_appstore do
    # Set up App Store Connect API key
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_filepath: "AuthKey.p8",
      in_house: false
    )

    build_app(
      workspace: "App.xcworkspace",
      scheme: "Shift Scan",
      configuration: "Release",
      export_method: "app-store",
      output_directory: "build",
      output_name: "ShiftScan-AppStore.ipa",
      skip_package_ipa: false,
      skip_package_pkg: true,
      derived_data_path: "build/DerivedData",
      xcargs: "-allowProvisioningUpdates"
    )
  end
end
