# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build development IPA for internal testing"
  lane :build_development do
   match(app_identifier: "com.shiftscanapp", type: "development", readonly: true, verbose: true)
   build_app(
     export_method: "development",
     workspace: "App.xcworkspace",
     scheme: "Shift Scan",
     configuration: "Debug",
     output_directory: "build",
     output_name: "ShiftScan-Development.ipa",
     verbose: true
   )
   # Optional: upload to TestFlight using API key file; comment out for pure local builds
  #  pilot(api_key_path: "fastlane/store.json", skip_waiting_for_build_processing: true)
  end
 

 
end
